name: Features
on:
  push:
    branches:
      - master
  

jobs:
  build:
    # strategy:
      # matrix:
        # platform: [aws]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt
    #- name: check fmt
    #  shell: bash
    #  run: |
    #    cargo fmt -- --check
    # - name: test_status
    #   env:
    #     DBG: true
    #   shell: bash
    #   run: |
    #     curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    #     make test_status
    ## It need to install protobuf-compiler for build environment.
    ## Enable this when build by container.
    # - name: Install protobuf-compiler
    #   shell: bash
    #   run: |
    #     apt install protobuf-compiler
    - name: install rustwasm
      shell: bash
      run: |
        echo "runing action"
   